/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const call_tool: (a: number, b: number, c: number, d: number, e: number) => void;
export const entity_history: (a: number, b: number, c: number) => void;
export const export_db: (a: number) => void;
export const install_opfs: () => number;
export const open: (a: number, b: number, c: number) => void;
export const open_from_bytes: (a: number, b: number, c: number) => void;
export const open_memory: (a: number) => void;
export const tool_definitions: (a: number) => void;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const rust_sqlite_wasm_abort: () => void;
export const rust_sqlite_wasm_assert_fail: (a: number, b: number, c: number, d: number) => void;
export const rust_sqlite_wasm_calloc: (a: number, b: number) => number;
export const rust_sqlite_wasm_malloc: (a: number) => number;
export const rust_sqlite_wasm_free: (a: number) => void;
export const rust_sqlite_wasm_getentropy: (a: number, b: number) => number;
export const rust_sqlite_wasm_localtime: (a: number) => number;
export const rust_sqlite_wasm_realloc: (a: number, b: number) => number;
export const sqlite3_os_end: () => number;
export const sqlite3_os_init: () => number;
export const __wasm_bindgen_func_elem_2136: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_1379: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export5: (a: number, b: number, c: number) => void;
